---
- name: Install updates
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # 1 hour
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
